[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyzzle-calendar-solver"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = ["black", "flake8", "pytest", "pytest-mock"]

# dev
[tool.black]
line-length = 88
